runtime: python39
entrypoint: gunicorn -b :$PORT mi_proyecto.wsgi

# Configuración opcional de escalado
instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 2

env_variables:
  DJANGO_SETTINGS_MODULE: "mi_proyecto.settings"
  SECRET_KEY: "tu_clave_secreta"
  DEBUG: "False"
