runtime: python39  # Cambia la versión de Python si usas otra

entrypoint: gunicorn -b :$PORT django-prueba.wsgi

handlers:
  - url: /static
    static_dir: static

  - url: /.*
    script: auto

env_variables:
  DJANGO_SETTINGS_MODULE: "django-prueba.settings"
